import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { prompt } = body

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    // Check if we have Google Cloud credentials
    if (!process.env.GOOGLE_CLOUD_PROJECT_ID || !process.env.GOOGLE_APPLICATION_CREDENTIALS) {
      console.log('🔄 Google Cloud not configured, falling back to DALL-E')
      return await fallbackToDallE(prompt)
    }

    try {
      // Use Google Imagen via Vertex AI
      const imageUrl = await generateImageWithImagen(prompt)
      
      return NextResponse.json({
        imageUrl,
        provider: 'google-imagen',
        metadata: {
          model: 'imagen-3',
          enhancedPrompt: prompt
        }
      })
    } catch (imagenError) {
      console.error('❌ Google Imagen failed:', imagenError)
      console.log('🔄 Falling back to DALL-E')
      return await fallbackToDallE(prompt)
    }

  } catch (error) {
    console.error('❌ Image generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate image' },
      { status: 500 }
    )
  }
}

async function generateImageWithImagen(prompt: string): Promise<string> {
  const { VertexAI } = await import('@google-cloud/vertexai')
  
  // Initialize Vertex AI with environment variable for credentials
  const vertexAI = new VertexAI({
    project: process.env.GOOGLE_CLOUD_PROJECT_ID,
    location: 'us-central1',
  })

  const generativeModel = vertexAI.getGenerativeModel({
    model: 'imagen-3',
  })

  // Enhanced prompt for cosmic/mystical imagery
  const enhancedPrompt = `Cosmic, ethereal, mystical, warm golden light, magical atmosphere, fantasy elements, celestial vibes, otherworldly beauty, dreamlike quality, glowing effects, cosmic dust, stardust particles, aurora-like colors, mystical energy, enchanting, transcendent, divine light, heavenly glow, fantastical, surreal, mesmerizing, captivating, professional photography, high resolution, cinematic lighting, warm color palette, golden hour, magical realism, spiritual energy, cosmic wonder, ethereal glow, mystical aura, enchanting atmosphere, otherworldly, celestial beauty, divine inspiration, magical realism, warm and inviting, cosmically beautiful, fantastically stunning: ${prompt}`

  const result = await generativeModel.generateImages({
    prompt: enhancedPrompt,
    numberOfImages: 1,
    aspectRatio: 'ASPECT_RATIO_1_1',
    safetyFilterLevel: 'BLOCK_ONLY_HIGH',
    personGeneration: 'ALLOW_ADULT'
  })

  const image = result.response.candidates?.[0]?.generatedImage
  if (!image) {
    throw new Error('No image generated by Imagen')
  }

  // Convert base64 to data URL
  const base64Data = image.data
  const mimeType = image.mimeType || 'image/jpeg'
  
  return `data:${mimeType};base64,${base64Data}`
}

async function fallbackToDallE(prompt: string) {
  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/api/generate-image`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ prompt })
    })

    if (!response.ok) {
      throw new Error('DALL-E fallback failed')
    }

    const data = await response.json()
    return NextResponse.json({
      imageUrl: data.imageUrl,
      provider: 'dall-e-fallback',
      metadata: {
        model: 'dall-e-3',
        enhancedPrompt: prompt,
        fallback: true
      }
    })
  } catch (error) {
    console.error('❌ DALL-E fallback failed:', error)
    return NextResponse.json(
      { error: 'All image generation methods failed' },
      { status: 500 }
    )
  }
}
