import { Logo } from '@/components/Logo'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | Timeline Alchemy',
  description: 'Terms of Service for Timeline Alchemy - Learn about the terms and conditions for using our platform.',
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-black to-gray-900">
      {/* Header */}
      <header className="bg-gray-900 shadow-sm border-b border-gray-800">
        <div className="container mx-auto px-4 py-4">
          <div className="flex justify-between items-center">
            <Link href="/">
              <Logo size="md" showText={false} />
            </Link>
            <Link href="/">
              <Button variant="outline">Back to Home</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
        
        <div className="prose prose-invert max-w-none space-y-6 text-gray-200">
          <p className="text-lg">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">1. Agreement to Terms</h2>
            <p>
              By accessing or using Timeline Alchemy ("the Platform," "we," "our," or "us"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">2. Description of Service</h2>
            <p>
              Timeline Alchemy is an AI-powered content creation platform that enables users to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate blog posts, articles, and social media content using artificial intelligence</li>
              <li>Create AI-generated images for content</li>
              <li>Schedule and publish content across multiple social media platforms</li>
              <li>Manage content creation for multiple organizations or clients</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">3. Account Registration</h2>
            <p>To use our Platform, you must:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Be at least 16 years of age</li>
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and update your account information</li>
              <li>Maintain the security of your password and account</li>
              <li>Accept responsibility for all activities that occur under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">4. Subscription and Payment</h2>
            <p>
              Timeline Alchemy offers subscription-based access to the Platform:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Basic Plan:</strong> €129/month - 1 organization, 4 blog posts + cross-platform social links per week</li>
              <li><strong>Pro Plan:</strong> €249/month - 1 organization, 8 blog posts + cross-platform social links (2 sets per week), advanced scheduling, analytics</li>
              <li><strong>Enterprise Plan:</strong> €499/month - Unlimited AI posts, priority support, custom integrations</li>
            </ul>
            <p className="mt-4">
              Payments are processed securely through Stripe. Subscriptions automatically renew unless cancelled. You may cancel at any time, but refunds are not provided for partial subscription periods.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">5. Content Ownership and License</h2>
            <p>
              <strong>Your Content:</strong> You retain all rights to the content you create using our Platform. By using the Platform, you grant us a limited license to process, store, and display your content solely to provide our services.
            </p>
            <p className="mt-4">
              <strong>AI-Generated Content:</strong> Content generated by our AI belongs to you. However, please note that AI-generated content may not be eligible for copyright protection in all jurisdictions. You are responsible for ensuring that any AI-generated content complies with applicable laws and does not infringe on third-party rights.
            </p>
            <p className="mt-4">
              <strong>Platform Content:</strong> All content, features, and functionality of the Platform (excluding your user-generated content) are owned by Timeline Alchemy and are protected by international copyright, trademark, and other intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">6. Acceptable Use Policy</h2>
            <p>You agree NOT to use the Platform to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate any laws or regulations</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable</li>
              <li>Generate spam, phishing content, or malicious material</li>
              <li>Impersonate any person or entity</li>
              <li>Attempt to gain unauthorized access to the Platform or related systems</li>
              <li>Interfere with or disrupt the Platform or servers</li>
              <li>Use automated systems to access the Platform in a manner that exceeds reasonable request volume</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">7. AI-Generated Content Disclaimer</h2>
            <p>
              Our Platform uses AI technology (OpenAI GPT-4 and DALL-E) to generate content. You acknowledge that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated content may contain errors, inaccuracies, or inconsistencies</li>
              <li>You are responsible for reviewing and verifying all AI-generated content before publication</li>
              <li>We do not guarantee the accuracy, completeness, or usefulness of AI-generated content</li>
              <li>You are responsible for ensuring AI-generated content complies with platform-specific guidelines and applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">8. Third-Party Platforms</h2>
            <p>
              When you connect social media accounts (Twitter, LinkedIn, Instagram, Facebook, YouTube, TikTok) to our Platform:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You authorize us to publish content on your behalf</li>
              <li>You remain responsible for all content published to your accounts</li>
              <li>You must comply with each platform's terms of service</li>
              <li>We are not responsible for changes to third-party platform APIs or policies</li>
              <li>You can revoke access at any time through your account settings</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, TIMELINE ALCHEMY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your use or inability to use the Platform</li>
              <li>Any unauthorized access to or use of your content</li>
              <li>Any content obtained from the Platform</li>
              <li>Errors, mistakes, or inaccuracies in AI-generated content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account and access to the Platform at our sole discretion, without notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties, or for any other reason.
            </p>
            <p className="mt-4">
              Upon termination, your right to use the Platform will immediately cease. You may delete your account at any time through your account settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">11. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms of Service at any time. We will notify you of any material changes by email or through the Platform. Your continued use of the Platform after such modifications constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">12. Governing Law</h2>
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of the Netherlands, without regard to its conflict of law provisions. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of the Netherlands.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mt-8 mb-4">13. Contact Information</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us:
            </p>
            <ul className="list-none space-y-2 mt-4">
              <li><strong>Email:</strong> <a href="mailto:timeline-alchemy@sh4m4ni4k.nl" className="text-yellow-400 hover:underline">timeline-alchemy@sh4m4ni4k.nl</a></li>
              <li><strong>Address:</strong> Poststraat 47B, 6371VL, Landgraaf, Netherlands</li>
            </ul>
          </section>

          <div className="mt-12 p-6 bg-gray-800 border border-gray-700 rounded-lg">
            <p className="text-sm">
              By using Timeline Alchemy, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-black text-gray-200 py-8 mt-16 border-t border-gray-800">
        <div className="container mx-auto px-4 text-center">
          <p className="text-sm">
            &copy; {new Date().getFullYear()} Timeline Alchemy. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}

